# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='last_use',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
