# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(to='main.UserProfile'),
        ),
    ]
