# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
